title: Citizens Review Archive
description: Public disclosure mirror, environmental asset data, and municipal cross-reference logs.
theme: jekyll-theme-hacker

plugins:
  - jekyll-sitemap
  - jekyll-feed

url: "https://5hw280543.github.io"
baseurl: "/citizens-review-archive"
